from pathlib import Path
import subprocess

from typer.testing import CliRunner
import yaml

from agentic_project_kit.cli import app


def test_init_output_preserves_dev_extra_marker(tmp_path):
    runner = CliRunner()

    result = runner.invoke(
        app,
        [
            "init",
            str(tmp_path / "demo-project"),
            "--type",
            "python-cli",
            "--description",
            "Demo project generated by Agentic Project Kit",
            "--license",
            "MIT",
        ],
    )

    assert result.exit_code == 0, result.output
    assert 'pip install -e ".[dev]"' in result.output
    assert 'pip install -e "."' not in result.output


def test_init_writes_project_contract_with_recommended_profiles(tmp_path):
    runner = CliRunner()
    target = tmp_path / "demo-project"

    result = runner.invoke(
        app,
        [
            "init",
            str(target),
            "--type",
            "python-cli",
            "--description",
            "Demo project generated by Agentic Project Kit",
            "--license",
            "MIT",
            "--no-github-actions",
            "--no-logging-evidence",
        ],
    )

    assert result.exit_code == 0, result.output
    contract_path = target / ".agentic" / "project.yaml"
    assert contract_path.exists()
    data = yaml.safe_load(contract_path.read_text(encoding="utf-8"))
    assert data["version"] == 1
    assert data["project"]["type"] == "python-cli"
    assert data["profiles"] == ["generic-git-repo", "markdown-docs", "python-cli"]
    assert data["policy_packs"] == ["starter", "solo-maintainer"]
    assert data["governance"]["doctor_before_merge"] is True


def test_init_accepts_explicit_profiles_and_policy_packs(tmp_path):
    runner = CliRunner()
    target = tmp_path / "demo-project"

    result = runner.invoke(
        app,
        [
            "init",
            str(target),
            "--type",
            "generic",
            "--description",
            "Demo project generated by Agentic Project Kit",
            "--profiles",
            "generic-git-repo,markdown-docs",
            "--policy-packs",
            "starter,documentation-governed",
        ],
    )

    assert result.exit_code == 0, result.output
    data = yaml.safe_load((target / ".agentic" / "project.yaml").read_text(encoding="utf-8"))
    assert data["profiles"] == ["generic-git-repo", "markdown-docs"]
    assert data["policy_packs"] == ["starter", "documentation-governed"]


def test_init_rejects_unknown_profile(tmp_path):
    runner = CliRunner()

    result = runner.invoke(
        app,
        [
            "init",
            str(tmp_path / "demo-project"),
            "--description",
            "Demo project generated by Agentic Project Kit",
            "--profiles",
            "does-not-exist",
        ],
    )

    assert result.exit_code != 0
    assert "unknown profile: does-not-exist" in result.output


def test_profile_explain_lists_profiles_and_policy_packs():
    runner = CliRunner()

    result = runner.invoke(app, ["profile-explain"])

    assert result.exit_code == 0
    assert "Project profiles:" in result.output
    assert "generic-git-repo" in result.output
    assert "python-cli" in result.output
    assert "governance-wrapper" in result.output
    assert "Policy packs:" in result.output
    assert "starter" in result.output
    assert "agentic-development" in result.output
    assert "output-contracts" in result.output


def test_workflow_status_reports_idle(tmp_path):
    runner = CliRunner()
    root = tmp_path / "repo"
    (root / ".agentic").mkdir(parents=True)
    (root / ".agentic" / "workflow_state").write_text("IDLE\n", encoding="utf-8")

    result = runner.invoke(app, ["workflow", "status", "--root", str(root)])

    assert result.exit_code == 0, result.output
    assert "workflow_state=IDLE" in result.output
    assert "current_work=missing" in result.output


def test_workflow_request_sets_current_work_requested_from_idle(tmp_path):
    runner = CliRunner()
    root = tmp_path / "repo"
    (root / ".agentic").mkdir(parents=True)
    (root / ".agentic" / "workflow_state").write_text("IDLE\n", encoding="utf-8")
    (root / ".agentic" / "current_work.yaml").write_text("name: demo\nsteps: []\n", encoding="utf-8")

    result = runner.invoke(app, ["workflow", "request", "--root", str(root)])

    assert result.exit_code == 0, result.output
    assert "Workflow request state: REQUESTED" in result.output
    assert "Next state: IDLE" in result.output
    assert (root / ".agentic" / "workflow_state").read_text(encoding="utf-8") == "IDLE\n"
    assert "state: REQUESTED" in (root / ".agentic" / "current_work.yaml").read_text(encoding="utf-8")


def test_workflow_cleanup_noops_from_idle(tmp_path):
    runner = CliRunner()
    root = tmp_path / "repo"
    (root / ".agentic").mkdir(parents=True)
    (root / ".agentic" / "workflow_state").write_text("IDLE\n", encoding="utf-8")

    result = runner.invoke(app, ["workflow", "cleanup", "--root", str(root)])

    assert result.exit_code == 0, result.output
    assert "workflow_state=IDLE" in result.output
    assert "No cleanup action available" in result.output


def test_workflow_cleanup_deletes_stale_local_evidence_branch_from_idle(tmp_path):
    runner = CliRunner()
    root = tmp_path / "repo"
    root.mkdir()
    subprocess.run(["git", "init"], cwd=root, check=True, capture_output=True, text=True)
    subprocess.run(["git", "config", "user.email", "test@example.com"], cwd=root, check=True)
    subprocess.run(["git", "config", "user.name", "Test User"], cwd=root, check=True)
    (root / ".agentic").mkdir(parents=True)
    (root / ".agentic" / "workflow_state").write_text("IDLE\n", encoding="utf-8")
    (root / "README.md").write_text("demo\n", encoding="utf-8")
    subprocess.run(["git", "add", "."], cwd=root, check=True)
    subprocess.run(["git", "commit", "-m", "Initial commit"], cwd=root, check=True, capture_output=True, text=True)
    subprocess.run(["git", "branch", "temp/workflow-evidence-test"], cwd=root, check=True)

    result = runner.invoke(app, ["workflow", "cleanup", "--root", str(root)])

    assert result.exit_code == 0, result.output
    assert "workflow_state=IDLE" in result.output
    assert "Cleaned stale workflow evidence branches: 1" in result.output
    branches = subprocess.run(
        ["git", "branch", "--list", "temp/workflow-evidence-*"],
        cwd=root,
        check=True,
        capture_output=True,
        text=True,
    )
    assert branches.stdout.strip() == ""


def test_init_accepts_governance_wrapper_type(tmp_path):
    runner = CliRunner()
    target = tmp_path / "demo-governance"

    result = runner.invoke(
        app,
        [
            "init",
            str(target),
            "--type",
            "governance-wrapper",
            "--description",
            "Governance wrapper demo",
            "--license",
            "MIT",
            "--github-actions",
            "--logging-evidence",
        ],
    )

    assert result.exit_code == 0, result.output
    data = yaml.safe_load((target / ".agentic" / "project.yaml").read_text(encoding="utf-8"))
    assert data["project"]["type"] == "governance-wrapper"
    assert "governance-wrapper" in data["profiles"]
    assert "output-contracts" in data["policy_packs"]


def test_init_governance_wrapper_next_steps_do_not_claim_python_install(tmp_path):
    runner = CliRunner()

    result = runner.invoke(
        app,
        [
            "init",
            str(tmp_path / "gov-project"),
            "--type",
            "governance-wrapper",
            "--description",
            "Governance wrapper project",
            "--license",
            "MIT",
        ],
    )

    assert result.exit_code == 0, result.output
    assert "agentic-kit check-docs" in result.output
    assert "agentic-kit doctor" in result.output
    assert "pip install -e" not in result.output
    assert "pytest -q" not in result.output


def test_cli_py_stays_as_root_registry() -> None:
    cli_text = Path("src/agentic_project_kit/cli.py").read_text(encoding="utf-8")
    assert len(cli_text.splitlines()) < 100
    assert "register_init_command(app)" in cli_text
    assert "register_profile_commands(app)" in cli_text
    assert "register_github_commands(app)" in cli_text
    assert "register_check_commands(app)" in cli_text
    assert "register_release_commands(app)" in cli_text
    assert "register_validation_commands(app)" in cli_text
    assert "def " not in cli_text
    assert "typer.Option" not in cli_text
    assert "typer.Argument" not in cli_text


def test_cli_commands_package_contains_command_groups() -> None:
    command_dir = Path("src/agentic_project_kit/cli_commands")
    expected = {
        "__init__.py",
        "init.py",
        "github.py",
        "profiles.py",
        "checks.py",
        "release.py",
        "pr_hygiene.py",
        "todo.py",
        "validation.py",
        "workflow.py",
    }
    assert expected.issubset({path.name for path in command_dir.iterdir()})
