from typer.testing import CliRunner
import yaml

from agentic_project_kit.cli import app


def test_init_output_preserves_dev_extra_marker(tmp_path):
    runner = CliRunner()

    result = runner.invoke(
        app,
        [
            "init",
            str(tmp_path / "demo-project"),
            "--type",
            "python-cli",
            "--description",
            "Demo project generated by Agentic Project Kit",
            "--license",
            "MIT",
        ],
    )

    assert result.exit_code == 0, result.output
    assert 'pip install -e ".[dev]"' in result.output
    assert 'pip install -e "."' not in result.output


def test_init_writes_project_contract_with_recommended_profiles(tmp_path):
    runner = CliRunner()
    target = tmp_path / "demo-project"

    result = runner.invoke(
        app,
        [
            "init",
            str(target),
            "--type",
            "python-cli",
            "--description",
            "Demo project generated by Agentic Project Kit",
            "--license",
            "MIT",
            "--no-github-actions",
            "--no-logging-evidence",
        ],
    )

    assert result.exit_code == 0, result.output
    contract_path = target / ".agentic" / "project.yaml"
    assert contract_path.exists()
    data = yaml.safe_load(contract_path.read_text(encoding="utf-8"))
    assert data["version"] == 1
    assert data["project"]["type"] == "python-cli"
    assert data["profiles"] == ["generic-git-repo", "markdown-docs", "python-cli"]
    assert data["policy_packs"] == ["starter", "solo-maintainer"]
    assert data["governance"]["doctor_before_merge"] is True


def test_init_accepts_explicit_profiles_and_policy_packs(tmp_path):
    runner = CliRunner()
    target = tmp_path / "demo-project"

    result = runner.invoke(
        app,
        [
            "init",
            str(target),
            "--type",
            "generic",
            "--description",
            "Demo project generated by Agentic Project Kit",
            "--profiles",
            "generic-git-repo,markdown-docs",
            "--policy-packs",
            "starter,documentation-governed",
        ],
    )

    assert result.exit_code == 0, result.output
    data = yaml.safe_load((target / ".agentic" / "project.yaml").read_text(encoding="utf-8"))
    assert data["profiles"] == ["generic-git-repo", "markdown-docs"]
    assert data["policy_packs"] == ["starter", "documentation-governed"]


def test_init_rejects_unknown_profile(tmp_path):
    runner = CliRunner()

    result = runner.invoke(
        app,
        [
            "init",
            str(tmp_path / "demo-project"),
            "--description",
            "Demo project generated by Agentic Project Kit",
            "--profiles",
            "does-not-exist",
        ],
    )

    assert result.exit_code != 0
    assert "unknown profile: does-not-exist" in result.output


def test_profile_explain_lists_profiles_and_policy_packs():
    runner = CliRunner()

    result = runner.invoke(app, ["profile-explain"])

    assert result.exit_code == 0
    assert "Project profiles:" in result.output
    assert "generic-git-repo" in result.output
    assert "python-cli" in result.output
    assert "governance-wrapper" in result.output
    assert "Policy packs:" in result.output
    assert "starter" in result.output
    assert "agentic-development" in result.output
    assert "output-contracts" in result.output

def test_init_accepts_governance_wrapper_type(tmp_path):
    runner = CliRunner()
    target = tmp_path / "demo-governance"

    result = runner.invoke(
        app,
        [
            "init",
            str(target),
            "--type",
            "governance-wrapper",
            "--description",
            "Governance wrapper demo",
            "--license",
            "MIT",
            "--github-actions",
            "--logging-evidence",
        ],
    )

    assert result.exit_code == 0, result.output
    data = yaml.safe_load((target / ".agentic" / "project.yaml").read_text(encoding="utf-8"))
    assert data["project"]["type"] == "governance-wrapper"
    assert "governance-wrapper" in data["profiles"]
    assert "output-contracts" in data["policy_packs"]



def test_init_governance_wrapper_next_steps_do_not_claim_python_install(tmp_path):
    runner = CliRunner()

    result = runner.invoke(
        app,
        [
            "init",
            str(tmp_path / "gov-project"),
            "--type",
            "governance-wrapper",
            "--description",
            "Governance wrapper project",
            "--license",
            "MIT",
        ],
    )

    assert result.exit_code == 0, result.output
    assert "agentic-kit check-docs" in result.output
    assert "agentic-kit doctor" in result.output
    assert "pip install -e" not in result.output
    assert "pytest -q" not in result.output
