from typer.testing import CliRunner

from agentic_project_kit.cli import app


def test_init_output_preserves_dev_extra_marker(tmp_path):
    runner = CliRunner()

    result = runner.invoke(
        app,
        [
            "init",
            str(tmp_path / "demo-project"),
            "--type",
            "python-cli",
            "--description",
            "Demo project generated by Agentic Project Kit",
            "--license",
            "MIT",
        ],
    )

    assert result.exit_code == 0, result.output
    assert 'pip install -e ".[dev]"' in result.output
    assert 'pip install -e "."' not in result.output
